version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pratti
    volumes:
      - dbdata:../PI-BackEnd/data:/var/lib/mysql

  back-end:
    build: ../PI-Backend/pesquisa
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pratti
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    command: >
      bash -c "dockerize -wait tcp://mysql:3306 -timeout 60s &&
      java -jar app.jar"

  front-end:
    build:
      context: /frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  web-server:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
      - 443:443
  volumes:
    - ./nginx/conf/:/etc/nginx/conf.d/:ro

volumes:
  - dbdata: